#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#
#What is the value of the first triangle number to have over five hundred divisors?

def triangle_number(n)
  (1..n).to_a.inject(0) { |sum,x| sum+=x }
end

def count_factors(x)
  sum = 0
  root = Math.sqrt(x)
  (1.upto root).each { |candidate| sum += 2 if x%candidate == 0 }
  sum
end

i=0
max = 0
while 1
  i+=1
  v = triangle_number(i)
  c = count_factors(v)
  if c > max
    puts "#{v} has #{c} factors"
    max = c
    break if c > 500
  end
end
