# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not 
# exceed four million.
previous = 1
current = 2
sum = 2

while (current <= 4000000) do
  tmp = current
  current += previous
  previous = tmp
  sum += current if current % 2 == 0
end

puts "Answer: #{sum}"